---
title: "Final Project Outline"
author: "Cameron Kay & Ashley Miller"
date: "4/28/2019"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_depth: 4
    toc_float: yes
---

### Chosen Format

For this project we would like to complete a brief, reproducible APA manuscript. The project will comprise the introduction section, method section, and the results section for an article investigating the relationship between the Dark Triad personality traits (narcissism, Machiavellianism, and psychopathy) and social media use.

### Purpose

The project will be substantive insofar that we will be producing an APA manuscript. We hypothesize that narcissism will be positively associated with frequency of social media use and time spent on social media, irrespective of site. We also expect that Machiavellianism will be negatively associated with frequency of social media use and time spent on social media. It is unclear how psychopathy will influence frequency of social media use and time spent on social media. 

A more exploratory aim of the project is to examine (1) whether one's reasons for using the internet and (2) perceptions of social media differ as a function of any of the Dark Triad traits. 

### Description of Data Source

```{r data_source}
# import data
data <- rio::import(here::here("data", "data_1.xlsx"), setclass = "tibble")

# show vs 6 rows of the dataset
head(data)
```

We will be using a dataset collected Winter Term (2019) through the Human Subjects Pool's general survey. Participants (*N* = `r nrow(data)`) were University of Oregon undergraduate students. The dataset includes (1) a measure of the Dark Triad personality traits (i.e., Machiavellianism, narcissism, psychopathy), (2) questions assessing  participants' frequency of visiting eleven social media sites, (3) questions assessing the amount of time participants spend on those eleven social media sites, (4) a scale assessing the participants' addiction to social media, (5) a scale measuring participants' reasons for using the internet, and (6) two questions assessing participants' overall view of social media sites. We will be focusing on the measure of the Dark Triad, the questions assessing frequency of use and amount of time spent on SMS.

### Lingering Questions

(1) We are able to run multiple models using map, but is there a simple way to vary the variables entered as predictors using map? For example, if we want to run every model between a null model and a full model?

### How we plan to address the main requirements for the final product:

No code is used repetitively (no more than twice) [10 points] / More than one variant of purrr::map is used [10 points] / At least two custom functions [20 points; 10 points each]

+ I imagine we will need to create a series of functions and such to ease the process of re-coding our variables and the data itself. We could probably find a way to use map when we need to exclude participants exhibiting low response deviations (i.e., an indicator of straight lining/clicking through the survey)?

At least one instance of parallel iteration (e.g., map2_*, pmap_*) [10 points] / At least one use case of purrr::nest %>% mutate() [10 points]

+ We could potentially do something similar to the plot iteration problem on the midterm.. maybe we could nest the data by Dark Triad trait and some other variable of interest, then create plots accordingly? 

Code is fully reproducible and housed on GitHub [10 points]

+ Already hosted on Github :) We will make sure the code is reproducible!




